CREATE DATABASE IF NOT EXISTS BD_APLICATIVO_DE_MUSICA_2ANO;
USE BD_APLICATIVO_DE_MUSICA_2ANO;

CREATE TABLE IF NOT EXISTS ARTISTA(
	CPF VARCHAR(255) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEPHONE VARCHAR (15) NOT NULL,
    ESTILO_MUSICAL VARCHAR (255) NOT NULL
);

CREATE TABLE IF NOT EXISTS GENERO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(500) NOT NULL,
    ESTILO_MUSICAL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ALBUM(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    QTD_MUSICAS VARCHAR(255) NOT NULL,
    CAPA BLOB NOT NULL,
    DATA_DO_ALBUM DATE NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(500) NOT NULL,
	FK_ARTISTA_CPF VARCHAR(20) NOT NULL,
    FOREIGN KEY (FK_ARTISTA_CPF) REFERENCES ARTISTA(CPF)
);

CREATE TABLE IF NOT EXISTS FAIXA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
	CAPA BLOB NOT NULL,
    ESTILO_MUSICAL VARCHAR(255) NOT NULL,
    LETRA VARCHAR(255) NOT NULL,
	FK_ALBUM_ID INTEGER NOT NULL,
    FK_GENERO_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_ALBUM_ID) REFERENCES ALBUM(ID),
    FOREIGN KEY (FK_GENERO_ID) REFERENCES GENERO(ID)
);
