CREATE DATABASE IF NOT EXISTS BD_LIVRO_DIGITAL_2ANO;
USE BD_LIVRO_DIGITAL_2ANO;

CREATE TABLE IF NOT EXISTS AUTOR(
	CPF INTEGER PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    EMAIL VARCHAR(500) NOT NULL,
    TELEPHONE VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS LEITOR(
	CPF INTEGER PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    EMAIL VARCHAR(500) NOT NULL,
    TELEPHONE VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS LIVRO_DIGITAL(
	ID INTEGER PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    VALOR VARCHAR(500) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    FK_AUTOR_CPF INTEGER NOT NULL,
    FOREIGN KEY (FK_AUTOR_CPF) REFERENCES AUTOR(CPF) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS LV_LEITOR(
	ID INTEGER PRIMARY KEY,
    FK_LEITOR_CPF INTEGER NOT NULL,
    FK_LIVRO_DIGITAL_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_DIGITAL_ID) REFERENCES DIGITAL(ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_LEITOR_CPF) REFERENCES LEITOR(CPF) ON DELETE CASCADE
);
