CREATE DATABASE IF NOT EXISTS BD_ENQUETES;
USE BD_ENQUETES;

CREATE TABLE IF NOT EXISTS USUARIO(
	USU_CODIGO INTEGER AUTO_INCREMENT,
    USU_DATA_CADASTRO DATE NOT NULL,
    USU_LOGIN VARCHAR(255) NOT NULL UNIQUE,
    USU_AREA_ATUACAO VARCHAR(500),
    USUS_PROFISSAO VARCHAR(500),
    USU_AREA_FORMACAO VARCHAR(500),
    USU_DATASC DATE NOT NULL,
    USU_ESTADO_CIVIL ENUM("SOLTEIRO", "CASADO","DIVORCIADO","VIÚVO") NOT NULL,
    USU_ESTADO VARCHAR(2) NOT NULL,
    USU_ESCOLARIDADE ENUM ("FUNDAMENTAL", "MÉDIO","SUPERIOR") NOT NULL,
    USU_EMAIL VARCHAR(255) NOT NULL UNIQUE,
    USU_SENHA VARCHAR(255) NOT NULL,
    USU_NOME VARCHAR(255) NOT NULL,
    PRIMARY KEY (USU_CODIGO)
);

CREATE TABLE IF NOT EXISTS ENQUETE(
	ENQ_CODIGO INTEGER AUTO_INCREMENT,
	ENQ_DATA_FINAL VARCHAR(500),
    ENQ_DATA_INICIAL VARCHAR(500) NOT NULL,
    ENQ_DESCRICAO VARCHAR(500) NOT NULL,
    ENQ_NOME VARCHAR (500) NOT NULL,
	FK_USU_CODIGO INTEGER NOT NULL,
    PRIMARY KEY (ENQ_CODIGO),
    FOREIGN KEY (FK_USU_CODIGO) REFERENCES USUARIO (USU_CODIGO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS USUARIO_RESPONDE_ENQUETE(
	URE_CODIGO INTEGER AUTO_INCREMENT,
	URE_DATA DATE NOT NULL,
    FK_USU_CODIGO INTEGER,
    FK_ENQ_CODIGO INTEGER,
    PRIMARY KEY (URE_CODIGO),
    FOREIGN KEY (FK_ENQ_CODIGO) REFERENCES ENQUETE (ENQ_CODIGO) ON DELETE CASCADE,
    FOREIGN KEY (FK_USU_CODIGO) REFERENCES USUARIO (USU_CODIGO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PERGUNTAS(
	PER_CODIGO INTEGER AUTO_INCREMENT,
    PER_DESCRICAO VARCHAR(500) NOT NULL UNIQUE,
    FK_ENQ_CODIGO INTEGER,
    PRIMARY KEY (PER_CODIGO),
    FOREIGN KEY (FK_ENQ_CODIGO) REFERENCES ENQUETE (ENQ_CODIGO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS RESPOSTAS(
	RES_CODIGO INTEGER AUTO_INCREMENT,
    RES_DESCRICAO VARCHAR(500) NOT NULL UNIQUE,
    RES_CERTA VARCHAR(1) NOT NULL,
    FK_PER_CODIGO INTEGER NOT NULL,
    PRIMARY KEY (RES_CODIGO),
    FOREIGN KEY (FK_PER_CODIGO) REFERENCES PERGUNTAS (PER_CODIGO) ON DELETE CASCADE
);


-- INSERT - INSERT
INSERT INTO  USUARIO(USU_DATA_CADASTRO,USU_LOGIN,USU_AREA_ATUACAO,USUS_PROFISSAO,USU_AREA_FORMACAO,USU_DATASC,USU_ESTADO_CIVIL,USU_ESTADO,USU_ESCOLARIDADE,USU_EMAIL,USU_SENHA,USU_NOME)
VALUES ("2021-02-12","anthony123","ESTUDANTE","MANICURE","nails designer","2009-02-26","SOLTEIRO","SP","MÉDIO","Anthony.azevedo@gmail.com","123456","Anthony");

INSERT INTO  USUARIO(USU_DATA_CADASTRO,USU_LOGIN,USU_AREA_ATUACAO,USUS_PROFISSAO,USU_AREA_FORMACAO,USU_DATASC,USU_ESTADO_CIVIL,USU_ESTADO,USU_ESCOLARIDADE,USU_EMAIL,USU_SENHA,USU_NOME)
VALUES ("2022-03-12","julia456","ESTUDANTE-2","MANICURE","nails designer","2007-08-18","CASADO","SP","MÉDIO","julia.azevedo@gmail.com","123456","Julia");

INSERT INTO  USUARIO(USU_DATA_CADASTRO,USU_LOGIN,USU_AREA_ATUACAO,USUS_PROFISSAO,USU_AREA_FORMACAO,USU_DATASC,USU_ESTADO_CIVIL,USU_ESTADO,USU_ESCOLARIDADE,USU_EMAIL,USU_SENHA,USU_NOME)
VALUES ("2023-04-12","geusiane789","ESTUDANTE-3","MANICURE","nails designer","2021-04-18","SOLTEIRO","SP","MÉDIO","geusiane.azevedo@gmail.com","123456","Geusiane");

-- INSERIR 
SELECT * FROM USUARIO;

-- INSERT - INSERT
INSERT INTO  ENQUETE(ENQ_DATA_FINAL,ENQ_DATA_INICIAL,ENQ_DESCRICAO,ENQ_NOME,FK_USU_CODIGO)
VALUES ("2025-12-25","2024-12-24","PERGUNTAS DIVERSAS QUE VÃO TE INTRETER","Qual animal é",1);

INSERT INTO  ENQUETE(ENQ_DATA_FINAL,ENQ_DATA_INICIAL,ENQ_DESCRICAO,ENQ_NOME,FK_USU_CODIGO)
VALUES ("2026-12-25","2025-12-24","PERGUNTAS DIVERSAS QUE VÃO TE INTRETER","Qual o objeto é",2);

INSERT INTO  ENQUETE(ENQ_DATA_FINAL,ENQ_DATA_INICIAL,ENQ_DESCRICAO,ENQ_NOME,FK_USU_CODIGO)
VALUES ("2027-12-25","2026-12-24","PERGUNTAS DIVERSAS QUE VÃO TE INTRETER","Qual esporte é",1);

-- INSERIR 
SELECT * FROM ENQUETE;

-- INSERT - INSERT
INSERT INTO  USUARIO_RESPONDE_ENQUETE(URE_DATA,FK_USU_CODIGO,FK_ENQ_CODIGO)
VALUES ("2018-05-12",1,1);

INSERT INTO  USUARIO_RESPONDE_ENQUETE(URE_DATA,FK_USU_CODIGO,FK_ENQ_CODIGO)
VALUES ("2017-06-15",2,1);

INSERT INTO  USUARIO_RESPONDE_ENQUETE(URE_DATA,FK_USU_CODIGO,FK_ENQ_CODIGO)
VALUES ("2016-07-11",3,3);

-- INSERIR 
SELECT * FROM USUARIO_RESPONDE_ENQUETE;

-- INSERT - INSERT
INSERT INTO  PERGUNTAS(PER_DESCRICAO,FK_ENQ_CODIGO)
VALUES ("qual a cor do cavalo branco de napoleão",1);

INSERT INTO  PERGUNTAS(PER_DESCRICAO,FK_ENQ_CODIGO)
VALUES ("Qual a cor da joaninha",2);

INSERT INTO  PERGUNTAS(PER_DESCRICAO,FK_ENQ_CODIGO)
VALUES ("O que é azul royal",3);

-- INSERIR 
SELECT * FROM PERGUNTAS;


-- INSERT - INSERT
INSERT INTO  RESPOSTAS(RES_DESCRICAO,RES_CERTA,FK_PER_CODIGO)
VALUES ("Branco");



-- INSERIR 
SELECT * FROM PERGUNTAS;
DROP DATABASE BD_ENQUETES;