CREATE DATABASE IF NOT EXISTS BD_GERENCIAR_PROJETOS_2ANO;
USE BD_GERENCIAR_PROJETOS_2ANO;

CREATE TABLE IF NOT EXISTS PROJETO(
	ID INTEGER PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
	DESCRICAO VARCHAR(500) NOT NULL,
    DATA_DO_PROJETO DATE NOT NULL,
    ORCAMENTO VARCHAR(500) NOT NULL
);

CREATE TABLE IF NOT EXISTS FUNCIONARIO(
	CPF VARCHAR(255) PRIMARY KEY,
	NOME VARCHAR (255) NOT NULL,
	TELEFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS TAREFA(
	ID INTEGER PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
	DESCRICAO VARCHAR(500) NOT NULL,
	DATA_DA_TAREFA DATE NOT NULL,
    FK_PROJETO_ID INTEGER NOT NULL,
    FK_FUNCIONARIO_CPF VARCHAR(255) NOT NULL,
    FOREIGN KEY (FK_PROJETO_ID) REFERENCES PROJETO(ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_FUNCIONARIO_CPF) REFERENCES FUNCIONARIO(CPF) ON DELETE CASCADE
);

