CREATE DATABASE IF NOT EXISTS BD_RESERVA_DE_HOTEL_2ANO;
USE BD_RESERVA_DE_HOTEL_2ANO;

CREATE TABLE IF NOT EXISTS HOTEL(
	CNPJ INTEGER PRIMARY KEY,
	EMAIL VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS HOSPEDE(
	CPF INTEGER PRIMARY KEY,
	TELEPHONE VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS QUARTO(
	ID INTEGER PRIMARY KEY,
	NUMERO VARCHAR(255) NOT NULL,
	FOTO BLOB NOT NULL,
	FK_HOTEL_CNPJ INTEGER NOT NULL,
    FOREIGN KEY (FK_HOTEL_CNPJ) REFERENCES HOTEL(CNPJ) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS RESERVADO(
	ID INTEGER PRIMARY KEY,
	FK_QUARTO_ID INTEGER NOT NULL,
	FK_HOSPEDE_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_HOSPEDE_ID) REFERENCES HOSPEDE(ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_QUARTO_ID) REFERENCES QUARTO(ID) ON DELETE CASCADE
);
