CREATE DATABASE IF NOT EXISTS BD_STREAMING_VIDEO_2ANO;
USE BD_STREAMING_VIDEO_2ANO;

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INTEGER PRIMARY KEY,
    IDADE VARCHAR (255) NOT NULL,
    DESCRICAO VARCHAR(500) NOT NULL
);

CREATE TABLE IF NOT EXISTS VIDEO(
	ID INTEGER PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    TEMPO VARCHAR (255) NOT NULL,
    FK_CATEGORIA_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_CATEGORIA_ID) REFERENCES CATEGORIA(ID) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS VIZUALIZACAO(
	ID INTEGER PRIMARY KEY,
    INTERACAO INTEGER NOT NULL,
	FK_VIDEO_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_VIDEO_ID) REFERENCES VIDEO(ID) ON DELETE CASCADE
);