CREATE DATABASE IF NOT EXISTS BD_ALUGUEL_PRODUTOS;
USE BD_ALUGUEL_PRODUTOS;

CREATE TABLE IF NOT EXISTS CLIENTE(
	CLIENTE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
	EMAIL VARCHAR (255) NOT NULL,
    CPF VARCHAR (255) NOT NULL,
    NOME VARCHAR(500) NOT NULL,
    TELEPHONE VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTO(
	PRODUTO_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(500) NOT NULL,
	DESCRICAO VARCHAR (255) NOT NULL,
    PRECO DECIMAL NOT NULL,
    QTD_DISPONIVEL INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS ALUGUEL(
	ALUGUEL_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
	DATA_ALUGUEL DATE NOT NULL,
    DATA_DEVOLUCAO DATE NOT NULL,
    VALOR_TOTAL DECIMAL NOT NULL,
    FK_CLIENTE_ID INTEGER NOT NULL,
    FK_PRODUTO_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_CLIENTE_ID) REFERENCES CLIENTE(CLIENTE_ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_PRODUTO_ID) REFERENCES PRODUTO(PRODUTO_ID) ON DELETE CASCADE
);

-- DML - LINGUAGEM DE MANIPULAÇÃO
-- INSERT - INSERT
INSERT INTO CLIENTE (EMAIL,TELEPHONE,CPF,NOME)
VALUES ("email@email.com","19999999999","123456789","leo");

INSERT INTO CLIENTE (EMAIL,TELEPHONE,CPF,NOME)
VALUES ("anthony.azevedo@email.com","19999999999","49227279814","Anthony");

INSERT INTO cliente (NOME,EMAIL,TELEPHONE, CPF)
VALUES ("Gbriel","gabriel@email.com","1999999999","1234849");

-- SELECT - SELECIONAR
SELECT * FROM CLIENTE;