CREATE DATABASE IF NOT EXISTS BD_CONSULTAS_MEDICAS_2ANO;
USE BD_CONSULTAS_MEDICAS_2ANO;

CREATE TABLE IF NOT EXISTS MEDICO(
	CRM INTEGER PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
	TELEFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
	DESCRICAO VARCHAR(500) NOT NULL
);

CREATE TABLE IF NOT EXISTS PACIENTE(
	CPF INTEGER PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
	TELEFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
	QTD_DE_PACIENTE VARCHAR(500) NOT NULL
);

CREATE TABLE IF NOT EXISTS CONSULTA(
	ID INTEGER PRIMARY KEY,
	DATA_DA_CONSULTA DATE NOT NULL,
    HORARIO VARCHAR(255) NOT NULL,
	FK_MEDICO_CRM INTEGER NOT NULL,
	FK_PACIENTE_CPF INTEGER NOT NULL,
    FOREIGN KEY (FK_MEDICO_CRM) REFERENCES MEDICO(CRM) ON DELETE CASCADE,
    FOREIGN KEY (FK_PACIENTE_CPF) REFERENCES PACIENTE(CPF) ON DELETE CASCADE
);
