CREATE DATABASE IF NOT EXISTS BD_GESTAO_ESTOQUE_2ANO;
USE BD_GESTAO_ESTOQUE_2ANO;

CREATE TABLE IF NOT EXISTS FORNECEDOR(
	CNPJ VARCHAR(255) PRIMARY KEY,
    QTD VARCHAR (255) NOT NULL
);

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(500) NOT NULL,
    QTD VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    VALIDADE VARCHAR(255) NOT NULL,
    PRECO VARCHAR(500) NOT NULL,
    QTD VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    FOTO BLOB NOT NULL,
    FK_CATEGORIA_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_CATEGORIA_ID) REFERENCES CATEGORIA(ID)
);

CREATE TABLE IF NOT EXISTS FORNECE(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
	 FK_PRODUTO_ID INTEGER NOT NULL,
	FK_FORNECEDOR_CNPJ VARCHAR(255) NOT NULL,
    FOREIGN KEY (FK_FORNECEDOR_CNPJ) REFERENCES FORNECEDOR(CNPJ),
    FOREIGN KEY (FK_PRODUTO_ID) REFERENCES PRODUTO(ID)
    
);