USE BD_SUPERMERCADO_FUNCIONARIO_PRODUTO_CONSUMIDO;

INSERT INTO SUPERMERCADO (SUP_CNPJ, SUP_RAZAO_SOCIAL, SUP_TELEPHONE, SUP_EMAIL, SUP_ENDERECO_LOGRADOURO, SUP_ENDERECO_NUMERO, SUP_ENDERECO_CIDADE, SUP_ENDERECO_ESTADO)
VALUES ("98765432100005","Supermercado BomPreco","11987654321","contato@bompreco.com","Avenida Central","250","Sao Paulo","SP");

INSERT INTO SUPERMERCADO (SUP_CNPJ, SUP_RAZAO_SOCIAL, SUP_TELEPHONE, SUP_EMAIL, SUP_ENDERECO_LOGRADOURO, SUP_ENDERECO_NUMERO, SUP_ENDERECO_CIDADE, SUP_ENDERECO_ESTADO)
VALUES ("45678912300002","Supermercado Economico","21999887766","sac@economico.com","Rua das Palmeiras","75","Rio de Janeiro","RJ");

INSERT INTO SUPERMERCADO (SUP_CNPJ, SUP_RAZAO_SOCIAL, SUP_TELEPHONE, SUP_EMAIL, SUP_ENDERECO_LOGRADOURO, SUP_ENDERECO_NUMERO, SUP_ENDERECO_CIDADE, SUP_ENDERECO_ESTADO)
VALUES ("32165498700003","Supermercado Uniao","31988776655","contato@uniaosuper.com","Praca das Flores","12","Belo Horizonte","MG");

INSERT INTO SUPERMERCADO (SUP_CNPJ, SUP_RAZAO_SOCIAL, SUP_TELEPHONE, SUP_EMAIL, SUP_ENDERECO_LOGRADOURO, SUP_ENDERECO_NUMERO, SUP_ENDERECO_CIDADE, SUP_ENDERECO_ESTADO)
VALUES ("78912345600004","Supermercado PagueMenos","41999884422","paguemenos@supermercado.com","Rua das Acacias","340","Curitiba","PR");



INSERT INTO PRODUTO (PRO_ID, PRO_CODIGO_BARRAS, PRO_NOME, PRO_PESO, PRO_QUANTIDADE, PRO_PRECO, PRO_DATA_VALIDADE)
VALUES (1,"1234567891","Feijao Carioca 1kg",1.0,300,8.49,"2025-11-15");

INSERT INTO PRODUTO (PRO_ID, PRO_CODIGO_BARRAS, PRO_NOME, PRO_PESO, PRO_QUANTIDADE, PRO_PRECO, PRO_DATA_VALIDADE)
VALUES (2,"1234567892","Acucar Cristal 2kg",2.0,400,7.99,"2026-02-10");

INSERT INTO PRODUTO (PRO_ID, PRO_CODIGO_BARRAS, PRO_NOME, PRO_PESO, PRO_QUANTIDADE, PRO_PRECO, PRO_DATA_VALIDADE)
VALUES (3,"1234567893","Oleo de Soja 900ml",0.9,250,6.79,"2025-08-30");

INSERT INTO PRODUTO (PRO_ID, PRO_CODIGO_BARRAS, PRO_NOME, PRO_PESO, PRO_QUANTIDADE, PRO_PRECO, PRO_DATA_VALIDADE)
VALUES (4,"1234567894","Macarrao Espaguete 500g",0.5,350,4.29,"2026-03-12");



INSERT INTO CONSUMIDOR (CON_CPF, CON_NOME, CON_TELEPHONE, CON_EMAIL)
VALUES ("58392146720","MARIA CLARA","11987654321","maria.clara@gmail.com");

INSERT INTO CONSUMIDOR (CON_CPF, CON_NOME, CON_TELEPHONE, CON_EMAIL)
VALUES ("31784596209","JOAO PEDRO","21999887766","joao.pedro@hotmail.com");

INSERT INTO CONSUMIDOR (CON_CPF, CON_NOME, CON_TELEPHONE, CON_EMAIL)
VALUES ("72649813570","LUCAS ALMEIDA","31988776655","lucas.almeida@yahoo.com");

INSERT INTO CONSUMIDOR (CON_CPF, CON_NOME, CON_TELEPHONE, CON_EMAIL)
VALUES ("84521097364","ANA BEATRIZ","41999884422","ana.beatriz@outlook.com");



INSERT INTO FUNCIONARIO (FUN_CPF, FUN_NOME, FUN_DATA_NASCIMENTO, FUN_TELEPHONE, FUN_EMAIL, FUN_CARTEIRA_DE_TRABALHO, FUN_BANCO_AGENCIA, FUN_BANCO_CONTA, FUN_DATA_ADMISSAO, FUN_JORNADA_TRABALHO, FK_SUP_CNPJ)
VALUES ("41829563710","MARIA FERNANDA","1988-11-02","21999887766","maria.fernanda@bompreco.com","CTPS2345678RJ","001-2563","125478-9","2020-08-15","40h semanais","98765432100001");

INSERT INTO FUNCIONARIO (FUN_CPF, FUN_NOME, FUN_DATA_NASCIMENTO, FUN_TELEPHONE, FUN_EMAIL, FUN_CARTEIRA_DE_TRABALHO, FUN_BANCO_AGENCIA, FUN_BANCO_CONTA, FUN_DATA_ADMISSAO, FUN_JORNADA_TRABALHO, FK_SUP_CNPJ)
VALUES ("53729184605","JOAO LUCAS","1995-04-20","31988776655","joao.lucas@economico.com","CTPS3456789MG","237-4451","654321-2","2022-01-05","44h semanais","45678912300002");

INSERT INTO FUNCIONARIO (FUN_CPF, FUN_NOME, FUN_DATA_NASCIMENTO, FUN_TELEPHONE, FUN_EMAIL, FUN_CARTEIRA_DE_TRABALHO, FUN_BANCO_AGENCIA, FUN_BANCO_CONTA, FUN_DATA_ADMISSAO, FUN_JORNADA_TRABALHO, FK_SUP_CNPJ)
VALUES ("62938471500","ANA BEATRIZ","1998-09-10","41999884422","ana.beatriz@uniaosuper.com","CTPS4567890PR","104-3321","998877-5","2023-06-18","36h semanais","32165498700003");

INSERT INTO FUNCIONARIO (FUN_CPF, FUN_NOME, FUN_DATA_NASCIMENTO, FUN_TELEPHONE, FUN_EMAIL, FUN_CARTEIRA_DE_TRABALHO, FUN_BANCO_AGENCIA, FUN_BANCO_CONTA, FUN_DATA_ADMISSAO, FUN_JORNADA_TRABALHO, FK_SUP_CNPJ)
VALUES ("71529836470","PEDRO HENRIQUE","1986-07-25","11976543210","pedro.henrique@paguemenos.com","CTPS5678901SP","033-1789","334455-6","2019-11-22","44h semanais","78912345600004");



SELECT * FROM SUPERMERCADO;

/*
CONSULTAR O AUMENTO DE R$ 2,00 NO PREÇO DOS PRODUTOS COM PREÇO ATUAL >= R$ 5,00
*/

SELECT 	PRO_NOME AS "NOME", 
		PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
        PRO_PRECO AS "PREÇO ATUAL", 
        TRUNCATE((PRO_PRECO + 2),2) AS "PREÇO COM AJUSTE DE R$ 2,00"
FROM 	PRODUTO
WHERE 	PRO_PRECO >= 5;

/*
CONSULTAR A REDUÇÃO DE R$ 1,00 NO PREÇO DOS PRODUTOS
COM PREÇO ATUAL ABAIXO DE R$ 5,00 OU R$ 10,00
*/

SELECT	PRO_NOME AS "NOME"


/*
CONSULTAR COMO SERIA APLICAR UM DESCONTO DE 10% EM TODOS OS PRODUTOS
*/

SELECT	PRO_NOME AS "NOME",
		PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
        PRO_PRECO AS "PREÇO ATUAL",
        (PRO_PRECO - (PRO_PRECO * 0.1)) AS "PREÇO COM DESCONTO DE 10%"
FROM	PRODUTO;

/*AJUSTAR O ESTOQUE DE PRIMEIRO PRODUTO, DIVIDINDO PELA METADE*/
SELECT	PRO_ID,
		PRO_NOME,
        PRO_CODIGO_BARRAS,
        PRO_QUANTIDADE
FROM	PRODUTO;

UPDATE	PRODUTO
SET		PRO_QUANTIDADE = PRO_QUANTIDADE/2
WHERE PRO_ID = 1;

/*CONSULTAR TODOS OS PRODUTOS QUE TENHAM DATA DE VALIDAE ENTRE SETEMBRO DE 2025 E DEZEMBRO DE 2025*/
SELECT PRO_NOME AS "NOME",	
		PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
        PRO_DATA_VALIDADE AS "DATA DE VALIDADE"
FROM PRODUTO
WHERE PRO_DATA_VALIDADE BETWEEN '2025-0901' AND '2025-12-31';

/*CONSULTAR TODOS OS PRODUTOS QUE TENHAM PREÇOS MAIOR QUE R$10 OU MENOR QUE R$4*/
SELECT PRO_NOME AS "NOME",
		PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
        PRO_PRECO AS "PREÇO"
FROM	PRODUTO
WHERE PRO_PRECO >= 10 OR PRO_PRECO <= 4;
 
 /*CONSULTAR OS DDS E TELEPHONES DOS CINSUMIDORES SEPARADAMENTE*/
 
 SELECT CON_NOME AS "NOME DO CONSUMIDOR",
		CON_CPF AS "CPF DO CONSUMIDOR",
        SUBSTRING(CON_TELEPHONE,1,2) AS "DDD DO TELEPHONE",
        SUBSTRING(CON_TELEPHONE,3,9) AS "NUMERO DO TELEPHONE"
FROM	CONSUMIDOR;

/*GERAR UMA FRASE CONCATENANDO: RAZÃO SOCIAL, CNPJ, TELEPHONE E EMAIL*/

SELECT CONCAT("RAZÃO SOCIAL:",
				CONCAT(SUP_RAZAO_SOCIAL,
						CONCAT(" | CNPJ: ",
								CONCAT(SUP_CNPJ,
										CONCAT(" | TELEPHONE: ",
												CONCAT(SUP_TELEPHONE,
														CONCAT(" | EMAIL: ", SUP_EMAIL))))))) AS FRASE
FROM	SUPERMERCADO;

/*GERAR UMA CONSULTA QUE VERIFICA O STATUS DO ESTOQUE DOS PRODUTOS.
REGRAS:
1) PESO <= 5: PESO BAIXO
2) PESO > 5 E PESO <= 50: PESSO MÉDIO
3) PESO > 50: PESO ALTO*/

SELECT PRO_NOME AS "NOME DO PRODUTO",
		PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
        PRO_QUANTIDADE AS "QUANTIDADE",
        PRO_DATA_VALIDADE AS "DATA DE VALIDADE",
        PRO_PESO AS "PESO DO PRUTO",
        CASE
			WHEN PRO_PESO <= 5 THEN "PESO BAIXO"
            WHEN PRO_PESO > 5 AND PRO_PESO <= 50 THEN "PESO MÉDIO"
            WHEN PRO_PESO > 50 THEN "PESO ALTO"
		END AS "CLASSIFICAÇÃO DO PESO"
FROM	PRODUTO;

/*CONTAR QUANTOS CONSUMIDORES TEMOS CADASTRADOS*/

SELECT COUNT(*)
FROM	CONSUMIDOR;

/*CONTAR QUANTOS SUPERMERCADOS TEMOS CADASTRADOS*/

SELECT COUNT(*)
FROM	SUPERMERCADO;

/*CONTAR QUANTOS FUNCIONARIOS TEMOS CADASTRADOS*/

SELECT COUNT(*)
FROM	SUPERMERCADO;

/*CONTAR QUANTOS FUNCIONARIOS TEMOS CADASTRADOS*/

SELECT COUNT(*)
FROM	FUNCIONARIO;

/*CONTAR QUANTOS PRODUTO TEMOS CADASTRADOS*/

SELECT COUNT(*)
FROM	PRODUTO;

/*SOMAR O PREÇO TOTAL DE TODODS OS PRODUTOS CADASTRADOS*/

SELECT SUM(PRO_PRECO)
FROM	PRODUTO;

SELECT CONCAT("R$ ", TRUNCATE(SUM(PRO_PRECO),2)) AS "SOMA TOTAL"
FROM	PRODUTO;

/*CALCULAR A MÉDIA DE PREÇOS DOS PRODUTOS*/

SELECT AVG(PRO_PRECO)
FROM	PRODUTO;

SELECT CONCAT("R$ ",TRUNCATE(AVG(PRO_PRECO),2)) AS "MÉDI DE PREÇO"
FROM	PRODUTO;

/*SELECIONAR O PRODUTO MAIS CARO*/

SELECT MAX(PRO_PRECO)
FROM	PRODUTO;

/*SELECIONAR O ESTOQUE COM MAIOR QUANTIDADE*/

SELECT MAX(PRO_QUANTIDADE)
FROM	PRODUTO;

/*SELECIONAR O PRODUTO MAIS BARATO*/

SELECT MIN(PRO_PRECO)
FROM	PRODUTO;

/*SELECIONAR O ESTOQUE COM MENOR QUANTIDADE*/

SELECT MIN(PRO_QUANTIDADE)
FROM	PRODUTO;

/*SELECIONAR A DATA E HORA ATUAL*/

SELECT NOW() FROM DUAL;

SELECT FUN_NOME AS "NOME DO FUNVIONARIO",
		DATE_FORMAT(FUN_DATA_NASCIMENTO, "%d/%m/%Y") AS "DATA DE NASCIMENTO",
        TIMESTAMPDIFF(YEAR,FUN_DATA_NASCIMENTO,NOW()) AS "IDADE"
FROM	FUNCIONARIO;

/*FUNÇÕES MATEMATICAS:
ABS - VALOR ABSOLUTO DE UM NÚMERO
ROUND - ARREDONDAR
POWER - POTENCIA*/

SELECT ABS(-10),
		ROUND(PRO_PRECO) AS "PREÇO ARREDONDADO",
        POWER(PRO_PRECO,2) AS "PREÇO ELEVADOS AS QUADRADO"
FROM	PRODUTO;

/*UPPER, LOWER, TRIM*/

SELECT UPPER(FUN_NOME) AS "MAIÚSCULAS",
		LOWER(FUN_NOME) AS "MINÚCULAS",
        TRIM("      ANTHONY") AS "TIRANDO ESPEÇOS"
FROM	FUNCIONARIO;

SELECT PRO_QUANTIDADE,
		COUNT(*) AS "REPETIÇÕES"
FROM	PRODUTO
GROUP BY PRO_QUANTIDADE;

/*UNION*/
SELECT FUN_NOME,
		FUN_CPF
FROM    FUNCIONARIO
UNION
SELECT FUN_NOME,
		FUN_CPF
FROM	FUNCIONARIO;

SELECT * FROM PRODUTO;

/*UNION*/
SELECT	PRO_NOME
FROM	PRODUTO
UNION
SELECT	"Feijao Carioca 1kg"
FROM	DUAL
UNION
SELECT	"IORGUT DO BOB ESPONJA"
FROM	DUAL;

/*UNION*/
SELECT	PRO_NOME
FROM	PRODUTO
UNION	ALL
SELECT	"Feijao Carioca 1kg"
FROM	DUAL
UNION	ALL
SELECT	"IORGUT DO BOB ESPONJA"
FROM	DUAL;

/*SELECT COM WHERE*/
SELECT	FUN_NOME AS "NOME DO FUNCIONATRIO",
		FUN_CPF	AS "CPF DO FUNCIONARIO",
        FUN_DATA_NASCIMENTO	AS "DATA DE NASCIMENTO",
        TIMESTAMPDIFF(YEAR,FUN_DATA_NASCIMENTO,NOW()) AS "IDADE"
FROM	FUNCIONARIO
WHERE	TIMESTAMPDIFF(YEAR,FUN_DATA_NASCIMENTO,NOW()) >= 25
AND		TIMESTAMPDIFF(YEAR,FUN_DATA_NASCIMENTO,NOW())<= 35;

/**RETORNAR OS SUPERMERCADOS
			OS FUNCIONARIOS
            OS CONSUMIDORES COM EMAIL IGUAL A HOTMAIL OU OUTLOOK*/
            
SELECT	CON_NOME AS "NOME",
		CON_CPF	AS "CPF/CNPJ",
        CON_TELEPHONE	AS "TELEPHONE",
        CON_EMAIL	AS "EMAIL",
        "CONSUMIDOR"	AS "TIPO"
FROM	CONSUMIDOR
WHERE	UPPER(CON_EMAIL) LIKE "%HOTMAIL%"
OR 		UPPER(CON_EMAIL) LIKE "%OUTLOOK%"
UNION
SELECT	FUN_NOME		AS "NOME",
		FUN_CPF		AS "CPF/CNPJ",
		FUN_TELEPHONE		AS "TELEPHONE",
        FUN_EMAIL		AS "EMAIL",
        "FUNCIONARIO"	AS "TIPO"
FROM	FUNCIONARIO
WHERE	UPPER(FUN_EMAIL) LIKE "%EMAIL%"
OR 		UPPER(FUN_EMAIL) LIKE "%OUTLOOK%"
UNION
SELECT	SUP_RAZAO_SOCIAL AS "NOME",
		SUP_CNPJ		 AS "CPF/CNPJ",
        SUP_TELEPHONE	 AS "TELEPHONE",
        SUP_EMAIL		 AS "EMAIL",
        "SUPERMERCADO"	 AS "TIPO"
FROM	SUPERMERCADO
WHERE	UPPER(SUP_EMAIL) LIKE "%HOTEMAIL%"
OR 		UPPER(SUP_EMAIL) LIKE "%OUTLOOK%";

/*CROOS JOIN:
RETORNAR TODOS OS PRODUTOS E OS SUPERMERCADOS EM QUE SÃO VRNDIDOS*/
SELECT		PRODUTO.PRO_NOME				AS	"NOME",
			PRODUTO.PRO_CODIGO_BARRAS		AS	"CÓDIGO DE BARRAS",
			SUPERMERCADO.SUP_RAZAO_SOCIAL	AS	"RAZÂO SOCIAL"
FROM		SUPERMERCADO_PRODUTO
CROSS JOIN	SUPERMERCADO
CROSS JOIN	PRODUTO
WHERE		PRODUTO.PRO_ID = SUPERMERCADO_PRODUTO.FK_PRO_ID
AND			SUPERMERCADO.SUP_CNPJ = SUPERMERCADO_PRODUTO.FK_SUP_CNPJ;

/*INNER JOIN
RETORNAR APENAS OS PRODUTOS QUE FORAM COMPARADOS POR ALGUM CONSUMIDOR*/
SELECT	PRODUTO_CONSUMIDOR.PCO_ID	AS	"ID DA COMPRA",
		PRODUTO.PRO_NOME	AS	"NOME DO PRODUTO",
        PRODUTO.PRO_CODIGO_BARRAS	AS	"CÓDIGO DE BARRAS",
        CONSUMIDOR.CON_NOME	AS	"NOME DO CONSUMIDOR",
        CONSUMIDOR.CON_CPF	AS	"CPF DO CONSUMIDOR"
FROM	PRODUTO_CONSUMIDOR
INNER JOIN PRODUTO ON (PRODUTO_CONSUMIDOR.FK_PRO_ID = PRODUTO.PRO_ID)
INNER JOIN CONSUMIDOR ON (PRODUTO_CONSUMIDOR.FK_CON_CPF = CONSUMIDOR.CON_CPF);

/*EXERCICIO COM INNER JOIN
RETORNAR APENAS OS FÚNCIONARIOS QUE TRABALAHM EM UM SUPERMERCADO
RETORNAR O NOME DO FUNCIONARIO E O NOME DO SUPERMERCADO QUE ELE TRABALHA*/

SELECT	SUPERMERCADO.SUP_RAZAO_SOCIAL AS "RAZÃO SOCIAL",
		FUNCIONARIO.FUN_NOME AS "NOME DO FUNCIONARIO"
FROM	SUPERMERCADO
INNER JOIN FUNCIONARIO ON (SUPERMERCADO.SUP_CNPJ = FUNCIONARIO.FK_SUP_CNPJ);

/*EXERCICIO 2 COM INNER JOIN
RETORNAR APENAS OS PRODUTOS QUE EXISTAM EM UM SUPERMERCADO
RETORNAR O NOME DO PRODUTO E O NOME DO SUPERMERCADO QUE ELE ESTÁ DISPONIVEL*/

SELECT	PRODUTO.PRO_NOME,
		SUPERMERCADO.SUP_RAZAO_SOCIAL
FROM SUPERMERCADO_PRODUTO
INNER JOIN PRODUTO ON (PRODUTO.PRO_ID = SUPERMERCADO_PRODUTO.FK_PRO_ID)
INNER JOIN SUPERMERCADO ON (SUPERMERCADO.SUP_CNPJ = SUPERMERCADO_PRODUTO.FK_SUP_CNPJ);

/*LEFT JOIN*/

INSERT INTO PRODUTO (PRO_CODIGO_BARRAS,
					PRO_NOME,
                    PRO_PESO,
                    PRO_QUANTIDADE,
                    PRO_PRECO,
                    PRO_DATA_VALIDADE)
VALUE				("3333333",
					"KITKAT",
                    "30",
                    "1500",
                    4.50,
                    "2026-01-01");
                    
SELECT	PRODUTO.PRO_NOME,
		SUPERMERCADO.SUP_RAZAO_SOCIAL
FROM	PRODUTO
LEFT JOIN SUPERMERCADO_PRODUTO ON (PRODUTO.PRO_ID = SUPERMERCADO_PRODUTO.FK_PRO_ID)
LEFT JOIN SUPERMERCADO ON (SUPERMERCADO.SUP_CNPJ = SUPERMERCADO_PRODUTO.FK_SUP_CNPJ);

SELECT * FROM SUPERMERCADO;

SELECT	PRODUTO.PRO_NOME,
		SUPERMERCADO.SUP_RAZAO_SOCIAL
FROM	PRODUTO
RIGHT JOIN SUPERMERCADO_PRODUTO ON (PRODUTO.PRO_ID = SUPERMERCADO_PRODUTO.FK_PRO_ID)
RIGHT JOIN SUPERMERCADO ON (SUPERMERCADO.SUP_CNPJ = SUPERMERCADO_PRODUTO.FK_SUP_CNPJ);

/*SELECT COM LEFT JOIN E RIGHT JOIN*/
SELECT * 
FROM	(
			SELECT S.SUP_RAZAO_SOCIAL 	AS RAZAO_SOCIAL,
					F.FUN_NOME 			AS NOME_FUNCIONARIO,
                    P.PRO_NOME	 		AS NOME_PRODUTO,
                    C.CON_NOME 			AS NOME_CONSUMIDOR
			FROM	SUPERMERCADO S
            LEFT JOIN FUNCIONARIO F				ON (S.SUP_CNPJ = F.FK_SUP_CNPJ)
            LEFT JOIN SUPERMERCADO_PRODUTO SP 	ON (S.SUP_CNPJ = SP.FK_SUP_CNPJ)
            LEFT JOIN PRODUTO P 				ON (SP.FK_PRO_ID = P.PRO_ID)
            LEFT JOIN PRODUTO_CONSUMIDOR PC 	ON (P.PRO_ID = PC.FK_PRO_ID)
            LEFT JOIN CONSUMIDOR C 				ON (PC.FK_CON_CPF = C.CON_CPF)
            
            UNION
            
            SELECT S.SUP_RAZAO_SOCIAL 	AS RAZAO_SOCIAL,
					F.FUN_NOME 			AS NOME_FUNCIONARIO,
                    P.PRO_NOME	 		AS NOME_PRODUTO,
                    C.CON_NOME 			AS NOME_CONSUMIDOR
			FROM	SUPERMERCADO S
            RIGHT JOIN FUNCIONARIO F				ON (S.SUP_CNPJ = F.FK_SUP_CNPJ)
            RIGHT JOIN SUPERMERCADO_PRODUTO SP 	ON (S.SUP_CNPJ = SP.FK_SUP_CNPJ)
            RIGHT JOIN PRODUTO P 				ON (SP.FK_PRO_ID = P.PRO_ID)
            RIGHT JOIN PRODUTO_CONSUMIDOR PC 	ON (P.PRO_ID = PC.FK_PRO_ID)
            RIGHT JOIN CONSUMIDOR C 				ON (PC.FK_CON_CPF = C.CON_CPF)
) SELECT_EXTERNO
ORDER BY 	SELECT_EXTERNO.RAZAO_SOCIAL 	ASC,
			SELECT_EXTERNO.NOME_FUNCIONARIO DESC,
            SELECT_EXTERNO.NOME_PRODUTO 	ASC,
            SELECT_EXTERNO.NOME_CONSUMIDOR 	DESC;
            
            
 /*PRIMEIRO INNER JOIN*/           
SELECT		PRODUTO.PRO_NOME,			
			SUPERMERCADO.SUP_RAZAO_SOCIAL	
FROM		SUPERMERCADO_PRODUTO
INNER JOIN	SUPERMERCADO ON (SUPERMERCADO.SUP_CNPJ = SUPERMERCADO_PRODUTO.FK_SUP_CNPJ)
INNER JOIN	PRODUTO ON (PRODUTO.PRO_ID = SUPERMERCADO_PRODUTO.FK_PRO_ID);

/*SEGUNDO INNER JOIN*/
SELECT	SUPERMERCADO.SUP_RAZAO_SOCIAL,
		FUNCIONARIO.FUN_NOME
FROM	SUPERMERCADO
INNER JOIN FUNCIONARIO ON (SUPERMERCADO.SUP_CNPJ = FUNCIONARIO.FK_SUP_CNPJ);

/*TERCEIRO INNER JOIN*/
SELECT	CONSUMIDOR.CON_NOME,
		PRODUTO.PRO_NOME
FROM	PRODUTO_CONSUMIDOR
INNER JOIN PRODUTO ON (PRODUTO_CONSUMIDOR.FK_PRO_ID = PRODUTO.PRO_ID)
INNER JOIN CONSUMIDOR ON (PRODUTO_CONSUMIDOR.FK_CON_CPF = CONSUMIDOR.CON_CPF);

/*QUARTO INNER JOIN*/
SELECT		PRODUTO.PRO_NOME,
			CONSUMIDOR.CON_NOME
FROM		PRODUTO_CONSUMIDOR
INNER JOIN PRODUTO ON (PRODUTO_CONSUMIDOR.FK_PRO_ID = PRODUTO.PRO_ID)
INNER JOIN CONSUMIDOR ON (PRODUTO_CONSUMIDOR.FK_CON_CPF = CONSUMIDOR.CON_CPF);

/*QUINTO INNER JOIN*/
SELECT SUPERMERCADO.SUP_RAZAO_SOCIAL AS "RAZÃO SOCIAL",
		COUNT(PRODUTO.PRO_ID)
FROM	SUPERMERCADO_PRODUTO
INNER JOIN PRODUTO ON (SUPERMERCADO_PRODUTO.FK_PRO_ID = PRODUTO.PRO_ID)
INNER JOIN SUPERMERCADO ON (SUPERMERCADO.SUP_CNPJ = SUPERMERCADO_PRODUTO.FK_SUP_CNPJ)
GROUP BY SUPERMERCADO.SUP_RAZAO_SOCIAL;