CREATE DATABASE IF NOT EXISTS BD_RESERVAS_AEREAS_2ANO;
USE BD_RESERVAS_AEREAS_2ANO;

CREATE TABLE IF NOT EXISTS PASSAGEIRO(
	CPF VARCHAR(15) PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
	TELEFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSAPORTE VARCHAR (255) NOT NULL,
    DATA_NASCIMENTO VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ASSENTO(
	ID INTEGER PRIMARY KEY,
    NUMERO_DO_ASSENTO VARCHAR (255) NOT NULL,
    LOCAL_DO_ASSENTO VARCHAR (255) NOT NULL,
	FK_PASSAGEIRO_CPF VARCHAR (15) NOT NULL,
    FOREIGN KEY (FK_PASSAGEIRO_CPF) REFERENCES PASSAGEIRO(CPF)
);

CREATE TABLE IF NOT EXISTS VOUO(
	ID INTEGER PRIMARY KEY,
    NOME_DO_VOUO INTEGER NOT NULL,
    NUMERO_DO_VOUO VARCHAR (255) NOT NULL,
	FK_ASSENTO_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_ASSENTO_ID) REFERENCES ASSENTO(ID)
);